stages:
  get-smarteole-data:
    cmd: calkit xenv -n py -- python examples/download_flasc_data.py
    deps:
      - examples/download_flasc_data.py
    outs:
      - inputs/SMARTEOLE-WFC-open-dataset:
          cache: false
          persist: true
